dissemination/urls.py
from django.conf.urls import url
from dissemination import views


urlpatterns = [
    url(r'^dissemination_file/$', views.dissemination_file, name='dissemination_file'),
]

sistema/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.utils.translation import ugettext_lazy as _


from helpers.views.show_page import display_documents, display_reports, display_add_content

from .views import language_change
from activity import views as activity_views
from dissemination import views as dissemination_views
from person import views as person_views
from research import views as research_views
from scientific_mission import views as scientific_views

document_patterns = [
    url(r'^anexo5/$', scientific_views.anexo5, name='anexo5'),
    url(r'^anexo6/$', scientific_views.anexo6, name='anexo6'),
    url(r'^anexo7/$', scientific_views.anexo7, name='anexo7'),
    url(r'^anexo9/$', scientific_views.anexo9, name='anexo9'),
    url(r'^certificate/$', activity_views.project_activities_certificate, name='certificate'),
    url(r'^seminars_poster/$', activity_views.seminars_poster, name='seminars_poster'),
]

reports_patterns = [
    url(r'^academic_works/$', research_views.academic_works, name='academic_works'),
    url(r'^articles/$', research_views.articles_report, name='articles'),
    url(r'^dissemination/$', dissemination_views.dissemination_report, name='dissemination_report'),
    url(r'^meetings/$', activity_views.meetings_report, name='meetings_report'),
    url(r'^researchers/$', person_views.researchers, name='researchers_report'),
    url(r'^seminars/$', activity_views.seminars_report, name='seminars_report'),
    url(r'^scientific_mission/$', scientific_views.missions_report, name='missions_report'),
    url(r'^training_programs/$', activity_views.training_programs_report, name='training_programs_report'),
]

content_patterns = [
    url(r'^import_papers/$', research_views.import_papers, name='import_papers'),
    url(r'^citation_names/$', person_views.citation_names, name='citation_names'),
]

urlpatterns = [
    path('', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/password_reset/$', auth_views.PasswordResetView, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    url(r'^language/(?P<language_code>(?:(?:\w{2})|(?:\w{2}\-\w{2})))$', language_change, name='language_change'),
    url(r'^activity/', include('activity.urls')),
    url(r'^research/', include('research.urls')),
    url(r'^dissemination/', include('dissemination.urls')),
    url(r'^scientific_mission/', include('scientific_mission.urls')),
    url(r'^documents/$', display_documents, name='documents'),
    url(r'^documents/', include(document_patterns)),
    url(r'^reports/$', display_reports, name='reports'),
    url(r'^reports/', include(reports_patterns)),
    url(r'^add_content/$', display_add_content, name='add_content'),
    url(r'^add_content/', include(content_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
if 'suit' not in settings.INSTALLED_APPS:
    admin.site.index_template = 'admin/default_index.html'
    admin.site.app_index_template = 'admin/default_index.html'
    admin.site.index_title = _('Features of the NIRA system')

member/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from validation import CPF
from django.db.models import signals
from django.contrib.auth.models import User

# Create your models here.

# Defining types of person
PROJECT_MEMBER = 'm'
OTHER = 'o'
PERSON = (
    (PROJECT_MEMBER, _('Member')),
    (OTHER, _('Other')),
)


def validate_cpf(value):
    """
    Checks if the CPF is valid

    """
    validation = CPF(value)
    if not validation.isValid():
        raise ValidationError(_('%s is not a valid CPF') % value)


class Role(models.Model):
    """
    An instance of this class is the role of a user.

    '__unicode__'		Returns the name.
    'class Meta'		Sets the description (singular and plural) model and the ordering of data by name.
    """
    name = models.CharField(_('Name'), max_length=255)

    # Returns the name
    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Role')
        verbose_name_plural = _('Roles')
        ordering = ('name', )


class InstitutionType(models.Model):
    """
    An instance of this class is the type of institution.

    '__unicode__'		Returns the name.
    'class Meta'		Sets the description (singular and plural) model and the ordering of data by name.
    """
    name = models.CharField(_('Name'), max_length=255)

    # Returns the name
    def __unicode__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Type of institution')
        verbose_name_plural = _('Types of institution')
        ordering = ('name', )


class Institution(models.Model):
    """
    An instance of this class represents an institution.

    '__unicode__'		Returns the acronym or the name.
    'class Meta'		Sets the description (singular and plural) model and the ordering of data by acronym.
    """
    name = models.CharField(_('Name'), max_length=255)
    acronym = models.CharField(_('Acronym'), max_length=50, blank=True, null=True)
    type = models.ForeignKey(InstitutionType, verbose_name=_('Type'))
    belongs_to = models.ForeignKey('self', verbose_name=_('Belongs to'), blank=True, null=True)

    # If exists, returns the acronym, if not returns the name
    def __unicode__(self):
        if self.belongs_to:
            if self.acronym:
                return u'%s-%s' % (self.acronym, self.belongs_to)
            else:
                return u'%s-%s' % (self.name, self.belongs_to)
        else:
            if self.acronym:
                return u'%s' % self.acronym
            else:
                return u'%s' % self.name

    class Meta:
        verbose_name = _('Institution')
        verbose_name_plural = _('Institutions')
        ordering = ('-acronym',)


class Person(models.Model):
    institution = models.ForeignKey(Institution, verbose_name=_('Institution'), blank=True, null=True)
    citation_name = models.CharField(_('Name in bibliographic citation'), max_length=255, blank=True, null=True,
                                     help_text='E.g.: Silva, J.')
    rg = models.CharField(_('RG'), max_length=12, blank=True, null=True)
    cpf = models.CharField(_('CPF'), blank=True, null=True, max_length=15, validators=[validate_cpf])
    passport = models.CharField(_('Passport'), max_length=12, blank=True, null=True)
    phone = models.CharField(_('Phone'), max_length=15, blank=True, null=True)
    cellphone = models.CharField(_('Cell Phone'), max_length=15, blank=True, null=True)
    zipcode = models.CharField(_('Zip Code'), max_length=9, blank=True, null=True)
    street = models.CharField(_('Address'), max_length=255, blank=True, null=True)
    street_complement = models.CharField(_('Complement'), max_length=255, blank=True, null=True)
    number = models.CharField(_('Number'), max_length=10, blank=True, null=True)
    district = models.CharField(_('District'), max_length=255, blank=True, null=True)
    city = models.CharField(_('City'), max_length=255, blank=True, null=True)
    state = models.CharField(_('State'), max_length=255, blank=True, null=True)
    country = models.CharField(_('Country'), max_length=255, blank=True, null=True)
    type_of_person = models.CharField(_('Type of person'), max_length=1, choices=PERSON, blank=True)

     # Returns the name
    def __unicode__(self):
        if self.type_of_person == 'm':
            return u'%s %s' % (self.projectmember.user.first_name, self.projectmember.user.last_name)
        else:
            return u'%s' % self.other.full_name


class ProjectMember(Person):
    """
    An instance of this class represents a person that is member of the project.

    '__unicode__'		Returns the full name from User class.
    'class Meta'		Sets the description (singular and plural) model and the ordering of data by user.
    'create_user_profile_signal' and 'password_change_signal' force password change on first login.
    """
    user = models.OneToOneField(User, verbose_name=_('User'))
    force_password_change = models.BooleanField(_('Force password change'), default=True,
                                                help_text=_('Force the user to change their password at next login.'))
    is_nira_admin = models.BooleanField(_('NIRA admin'), default=False,
                                        help_text=_('Designates whether the user can create content on behalf of '
                                                    'another user.'))
    role = models.ForeignKey(Role, verbose_name=_('Role'), blank=True, null=True)

    # Returns the full name from User class
    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)

    # Post_save signal that will create an Investigator every time a User is created.
    def create_user_profile_signal(sender, instance, created, **kwargs):
        if created:
            ProjectMember.objects.create(user=instance)

    # If user exists and he is not superuser, checks if the password was changed to modify
    # force_password_change to False.
    def password_change_signal(sender, instance, **kwargs):
        try:
            if User.objects.all().count() == 0:
                return

            user = User.objects.get(username=instance.username)

            if user.is_superuser:
                return

            if not user.password == instance.password:
                profile, created = ProjectMember.objects.get_or_create(user=user)
                profile.force_password_change = False
                profile.save()
        except User.DoesNotExist:
            pass

    signals.pre_save.connect(password_change_signal, sender=User, dispatch_uid='accounts.models')
    signals.post_save.connect(create_user_profile_signal, sender=User, dispatch_uid='accounts.models')

    # Description of the model / Sort by user
    class Meta:
        verbose_name = _('Member - Info')
        verbose_name_plural = _('Members - Info')
        ordering = ('user', )

    # Sets the type of person as member
    def save(self, *args, **kwargs):
        self.type_of_person = PROJECT_MEMBER
        super(ProjectMember, self).save(*args, **kwargs)


class Other(Person):
    """
    An instance of this class represents a person who has developed some work for the project.

    '__unicode__'		Returns the full name.
    'class Meta'		Sets the description (singular and plural) model and the ordering of data by name.
    """
    full_name = models.CharField(_('Full name'), max_length=255)
    email = models.EmailField(_('Email'), blank=True, null=True)

    # Returns the name
    def __unicode__(self):
        return u'%s' % self.full_name

    class Meta:
        verbose_name = _('Other person - Info')
        verbose_name_plural = _('Other persons - Info')
        ordering = ('full_name', )

    # Sets the type of person as other
    def save(self, *args, **kwargs):
        self.type_of_person = OTHER
        super(Other, self).save(*args, **kwargs)

dissemination/forms.py
from django import forms
from django.forms import TextInput
from dissemination.models import Dissemination


class DisseminationForm(forms.ModelForm):

    class Meta:
        model = Dissemination
        fields = ['link']
        widgets = {
            'link': TextInput(attrs={'size': 55, 'placeholder': 'neuromat.numec.prp.usp.br/example'}),
        }

dissemination/views.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _

from helpers.views.date import now_plus_thirty
from helpers.views.latex import escape_and_generate_latex
from helpers.views.pdf import render as render_to_pdf
from dissemination.models import Dissemination, Internal, InternalMediaOutlet, TYPE_OF_MEDIA


def internal_filter(internal_type, start_date, end_date):
    disseminations = Internal.objects.filter(media_outlet_id=internal_type, date__gte=start_date,
                                             date__lte=end_date).order_by('-date')
    return disseminations


def external_filter(start_date, end_date):
    disseminations = Dissemination.objects.filter(type_of_media='e', date__gte=start_date,
                                                  date__lte=end_date).order_by('-date')
    return disseminations


def validate_start_date(request):
    try:
        if request.POST['start_date'] == '':
            start_date = datetime.datetime.strptime('19700101 00:00:00', '%Y%m%d %H:%M:%S').date()
        else:
            start_date = datetime.datetime.strptime(request.POST['start_date'], "%d/%m/%Y").date()
    except ValueError:
        start_date = False

    return start_date


def validate_end_date(request):
    try:
        if request.POST['end_date'] == '':
            end_date = now_plus_thirty()
        else:
            end_date = datetime.datetime.strptime(request.POST['end_date'], "%d/%m/%Y").date()
    except ValueError:
        end_date = False

    return end_date


@login_required
def dissemination_report(request):

    types = [{'value': media_type[0], 'display': media_type[1]} for media_type in TYPE_OF_MEDIA]
    internal_types = InternalMediaOutlet.objects.all()
    internal_types = [{'value': media.id, 'display': media.name} for media in internal_types]
    internal_type = ''

    if request.method == 'POST':
        media_type = request.POST['type']

        start_date = validate_start_date(request)
        end_date = validate_end_date(request)

        if media_type != '0':
            if start_date and end_date and end_date >= start_date:
                disseminations = ''
                media_name = ''

                if media_type == 'i':
                    internal_type = request.POST['internal_type']
                    disseminations = internal_filter(internal_type, start_date, end_date)
                    media_name = InternalMediaOutlet.objects.get(id=internal_type).name

                else:
                    disseminations = external_filter(start_date, end_date)
                    media_name = ''

                context = {'start_date': start_date,
                           'end_date': end_date,
                           'disseminations': disseminations,
                           'type': media_type,
                           'media_name': media_name,
                           'internal_type': internal_type}

                return render(request, 'report/dissemination/dissemination_report.html', context)

            else:
                messages.error(request, _('You entered a wrong date format or the end date is not greater than or equal'
                                          ' to the start date.'))

        else:
            messages.error(request, _('You should choose a type.'))

    context = {'types': types, 'internal_types': internal_types}

    return render(request, 'report/dissemination/dissemination.html', context)


@login_required
def dissemination_file(request):

    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    media_type = request.GET.get('type')
    internal_type = request.GET.get('internal_type')
    filename = request.GET.get('filename')
    extension = request.GET.get('extension')

    if media_type == 'i':

        disseminations = internal_filter(internal_type, start_date, end_date)
        internal_media = InternalMediaOutlet.objects.get(pk=internal_type)
        media = internal_media.name
        context = {'disseminations': disseminations, 'type': media_type, 'media': media, 'media_name': media,
                   'extension': extension}

    else:
        disseminations = external_filter(start_date, end_date)
        context = {'disseminations': disseminations, 'type': media_type, 'extension': extension}

    if extension == ".tex":
        return escape_and_generate_latex('report/dissemination/tex/disseminations.tex', context, filename, table=True)

    return render_to_pdf('report/dissemination/pdf/dissemination.html', context, 'reports.css')

templates/report/dissemination/dissemination.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/masked_input/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'js/dissemination.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Dissemination' %}</span></div>
{% endblock %}

{% block content %}
<form role="form" method="post">{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-2 col-sm-2">
            <label>{% trans "Type" %}</label>
            <select class="form-control" name="type" id="id_type">
                <option value="0">-------</option>
                {% for type in types %}
                    <option value="{{ type.value }}">{{ type.display }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col-xs-2 col-sm-2" id="id_class_internal_field">
            <label>{% trans "Media outlet" %}</label>
            <select class="form-control" name="internal_type" id="id_internal_type">
                {% for type in internal_types %}
                    <option value="{{ type.value }}">{{ type.display }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col-xs-2 col-sm-2">
            <label>{% trans "Start date" %}</label>
            <input class="datepicker report-date-mask" autocomplete="off" name="start_date" id="id_start_date">
        </div>

        <div class="col-xs-2 col-sm-2">
            <label>{% trans "End date" %}</label>
            <input class="datepicker report-date-mask" autocomplete="off" name="end_date" id="id_end_date">
        </div>

        <div class="col-xs-3 col-sm-3">
            <br>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary btn-lg" style="font-size:16px;" role="button" \
                        id="submit">{% trans "Get report" %}</button>
             </div>
        </div>
    </div>


</div>
</form>

{% endblock %}

templates/report/dissemination/dissemination_report.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="/">{% trans 'Home' %}</a> ›
        <a href="/reports">{% trans 'Reports' %}</a> ›
        <a href="/reports/dissemination">{% trans 'Dissemination' %}</a> ›
        <span class="active">{% trans 'Dissemination report' %}</span></div>
{% endblock %}

{% block content %}
{% if disseminations %}

    <p>
        <a class="btn btn-primary" href="{% url 'dissemination_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&type={{ type }}&internal_type={{ internal_type }}&filename=external&extension=.tex"><i class="icon-download icon-white"></i> {% trans 'Download .tex file' %}</a>
        <a class="btn btn-primary" href="{% url 'dissemination_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&type={{ type }}&internal_type={{ internal_type }}&filename=external&extension=.pdf"><i class="icon-download icon-white"></i> {% trans 'Download .pdf file' %}</a>
    </p>

    {% if type == 'e' %}

        <table class="table table-striped table-bordered">
        <tr>
            <th width="30%">{% trans "Title" %}</th>
            <th width="20%">{% trans "Authors" %}</th>
            <th width="15%">{% trans "Media outlet" %}</th>
            <th width="25%">{% trans "Topics" %}</th>
            <th width="10%">{% trans "Date" %}</th>
        </tr>
        {% for dissemination in disseminations %}
            <tr>
                {% if type == 'e'%}
                    {% if dissemination.link %}
                        <td><a href="{{ dissemination.link }}" target="_blank">{{ dissemination.title }}</a></td>
                    {% else %}<td>{{ dissemination.title }}</td>{% endif %}
                    <td>{{ dissemination.external.authors }}</td>
                    <td>{{ dissemination.external.media_outlet }}</td>
                    <td>{{ dissemination.topics }}</td>
                    <td>{{ dissemination.date|date:"M d, Y" }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
        <div><strong>Total:</strong> {{ disseminations|length }}</div>

    {% elif type == 'i'%}

        <table class="table table-striped table-bordered">

        {% if media_name  %}
            <div class="text-center"><strong>{{ media_name }}</strong></div><br>
        {% endif %}

        {% if media_name != 'Newsletter' %}
            <tr>
                <th width="40%">{% trans "Title" %}</th>
                <th width="25%">{% trans "Authors" %}</th>
                <th width="25%">{% trans "Topics" %}</th>
                <th width="10%">{% trans "Date" %}</th>
            </tr>
        {% else %}
            <tr>
                <th width="50%">{% trans "Title" %}</th>
                <th width="30%">{% trans "Topics" %}</th>
                <th width="20%">{% trans "Date" %}</th>
            </tr>
        {% endif %}
        {% for dissemination in disseminations %}
            <tr>
                {% if dissemination.link %}
                    <td><a href="{{ dissemination.link }}" target="_blank">{{ dissemination.title }}</a></td>
                {% else %}<td>{{ dissemination.title }}</td>{% endif %}
                {% if media_name != 'Newsletter' %}<td>{{ dissemination.authors }}</td>{% endif %}
                <td>{{ dissemination.topics }}</td>
                <td>{{ dissemination.date|date:"M d, Y" }}</td>
            </tr>
        {% endfor %}
        </table>
        <div><strong>Total:</strong> {{ disseminations|length }}</div>
    {% endif %}

{%  else %}
    {% trans "No disseminations found!" %}
{% endif %}
{% endblock %}