activity/urls.py
from django.conf.urls import url
from activity import views


urlpatterns = [
    url(r'^seminars_show_titles/$', views.seminars_show_titles, name='seminars_show_titles'),

    #  files
    url(r'^seminars_file/$', views.seminars_file, name='seminars_file'),
    url(r'^training_programs_file/$', views.training_programs_file, name='training_programs_file'),
]

sistema/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.utils.translation import ugettext_lazy as _


from helpers.views.show_page import display_documents, display_reports, display_add_content

from .views import language_change
from activity import views as activity_views
from dissemination import views as dissemination_views
from person import views as person_views
from research import views as research_views
from scientific_mission import views as scientific_views

document_patterns = [
    url(r'^anexo5/$', scientific_views.anexo5, name='anexo5'),
    url(r'^anexo6/$', scientific_views.anexo6, name='anexo6'),
    url(r'^anexo7/$', scientific_views.anexo7, name='anexo7'),
    url(r'^anexo9/$', scientific_views.anexo9, name='anexo9'),
    url(r'^certificate/$', activity_views.project_activities_certificate, name='certificate'),
    url(r'^seminars_poster/$', activity_views.seminars_poster, name='seminars_poster'),
]

reports_patterns = [
    url(r'^academic_works/$', research_views.academic_works, name='academic_works'),
    url(r'^articles/$', research_views.articles_report, name='articles'),
    url(r'^dissemination/$', dissemination_views.dissemination_report, name='dissemination_report'),
    url(r'^meetings/$', activity_views.meetings_report, name='meetings_report'),
    url(r'^researchers/$', person_views.researchers, name='researchers_report'),
    url(r'^seminars/$', activity_views.seminars_report, name='seminars_report'),
    url(r'^scientific_mission/$', scientific_views.missions_report, name='missions_report'),
    url(r'^training_programs/$', activity_views.training_programs_report, name='training_programs_report'),
]

content_patterns = [
    url(r'^import_papers/$', research_views.import_papers, name='import_papers'),
    url(r'^citation_names/$', person_views.citation_names, name='citation_names'),
]

urlpatterns = [
    path('', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/password_reset/$', auth_views.PasswordResetView, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    url(r'^language/(?P<language_code>(?:(?:\w{2})|(?:\w{2}\-\w{2})))$', language_change, name='language_change'),
    url(r'^activity/', include('activity.urls')),
    url(r'^research/', include('research.urls')),
    url(r'^dissemination/', include('dissemination.urls')),
    url(r'^scientific_mission/', include('scientific_mission.urls')),
    url(r'^documents/$', display_documents, name='documents'),
    url(r'^documents/', include(document_patterns)),
    url(r'^reports/$', display_reports, name='reports'),
    url(r'^reports/', include(reports_patterns)),
    url(r'^add_content/$', display_add_content, name='add_content'),
    url(r'^add_content/', include(content_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
if 'suit' not in settings.INSTALLED_APPS:
    admin.site.index_template = 'admin/default_index.html'
    admin.site.app_index_template = 'admin/default_index.html'
    admin.site.index_title = _('Features of the NIRA system')

activity/models.py
from django.db import models
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _

from person.models import Person, Institution

# Defining the duration of a Training Program
ONE_HOUR = '1h'
ONE_AND_A_HALF_HOUR = '1h30'
TWO_HOURS = '2h'
TWO_AND_A_HALF_HOURS = '2h30'
THREE_HOURS = '3h'
THREE_AND_A_HALF_HOURS = '3h30'
FOUR_HOURS = '4h'
FOUR_AND_A_HALF_HOURS = '4h30'
FIVE_HOURS = '5h'
FIVE_AND_A_HALF_HOURS = '5h30'
SIX_HOURS = '6h'
SIX_AND_A_HALF_HOURS = '6h30'
SEVEN_HOURS = '7h'
SEVEN_AND_A_HALF_HOURS = '7h30'
EIGHT_HOURS = '8h'
EIGHT_AND_A_HALF_HOURS = '8h30'
NINE_HOURS = '9h'
NINE_AND_A_HALF_HOURS = '9h30'
TEN_HOURS = '10h'
OTHER = 'Other'
DURATION = (
    (ONE_HOUR, '1h'),
    (ONE_AND_A_HALF_HOUR, '1h30'),
    (TWO_HOURS, '2h'),
    (TWO_AND_A_HALF_HOURS, '2h30'),
    (THREE_HOURS, '3h'),
    (THREE_AND_A_HALF_HOURS, '3h30'),
    (FOUR_HOURS, '4h'),
    (FOUR_AND_A_HALF_HOURS, '4h30'),
    (FIVE_HOURS, '5h'),
    (FIVE_AND_A_HALF_HOURS, '5h30'),
    (SIX_HOURS, '6h'),
    (SIX_AND_A_HALF_HOURS, '6h30'),
    (SEVEN_HOURS, '7h'),
    (SEVEN_AND_A_HALF_HOURS, '7h30'),
    (EIGHT_HOURS, '8h'),
    (EIGHT_AND_A_HALF_HOURS, '8h30'),
    (NINE_HOURS, '9h'),
    (NINE_AND_A_HALF_HOURS, '9h30'),
    (TEN_HOURS, '10h'),
    (OTHER, _('Other duration time'))
)

# Defining types of activities
TRAINING_PROGRAM = 't'
MEETING = 'm'
SEMINAR = 's'
TYPE_OF_ACTIVITY = (
    (TRAINING_PROGRAM, _('Training Program')),
    (MEETING, _('Meeting')),
    (SEMINAR, _('Seminar')),
)


class ProjectActivities(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    local = models.ForeignKey(Institution, verbose_name=_('Local'), blank=True, null=True, on_delete=models.PROTECT)
    type_of_activity = models.CharField(_('Type of activity'), max_length=1, choices=TYPE_OF_ACTIVITY, blank=True)

    # pylint: disable=E1101
    def __str__(self):
        return u'%s - %s' % (self.get_type_of_activity_display(), self.title)

    class Meta:
        ordering = ('type_of_activity', 'title')


class News(models.Model):
    """
    An instance of this class is a link to a publication related to a project activity.

    'class Meta'		Sets the description model (singular and plural) and define ordering of data by url.
    """
    activity = models.ForeignKey(ProjectActivities, on_delete=models.CASCADE)
    url = models.URLField(_('URL'))

    def __str__(self):
        return u'%s' % self.url

    class Meta:
        verbose_name = _('Link')
        verbose_name_plural = _('Links')
        ordering = ('url', )


class Meeting(ProjectActivities):
    """
    An instance of this class is a meeting.

    'class Meta'		Sets the description model (singular and plural) and define ordering of data by start_date.
    """

    # fields
    broad_audience = models.BooleanField(_('Broad audience?'), default=False)
    cepid_event = models.BooleanField(_('Organized by CEPID?'), default=False)
    participant = models.ManyToManyField(Person, verbose_name=_('Participant'), blank=True)
    description = models.TextField(_('Description'), blank=True, null=True)
    start_date = models.DateField(_('Start date'))
    end_date = models.DateField(_('End date'))
    banner = models.ImageField(_('Banner'), upload_to='banners/', blank=True, null=True)

    class Meta:
        verbose_name = _('Meeting')
        verbose_name_plural = _('Meetings')
        ordering = ('-start_date', )

    # Sets the type of activity as Meeting
    # pylint: disable=W0221
    def save(self, *args, **kwargs):
        self.type_of_activity = MEETING
        super(Meeting, self).save(*args, **kwargs)


class TrainingProgram(ProjectActivities):
    """
    An instance of this class is a training program.

    'class Meta'		Sets the description model (singular and plural) and define ordering of data by start_date.
    'speakers'          Get the speakers of the training program and their institutions.
    """
    speaker = models.ManyToManyField(Person, verbose_name=_('Speaker'))
    belongs_to = models.ForeignKey(Meeting, verbose_name=_('Meeting'), blank=True, null=True, on_delete=models.PROTECT)
    description = models.TextField(_('Description'), blank=True, null=True)
    start_date = models.DateField(_('Start date'))
    end_date = models.DateField(_('End date'), blank=True, null=True)
    duration = models.CharField(_('Duration'), max_length=5, choices=DURATION)
    other_duration = models.CharField(_('Other duration time'), max_length=5, blank=True, null=True,
                                      help_text='E.g.: 11h or 11h30')
    number_of_participants = models.IntegerField(_('Number of participants'), blank=True, null=True)

    class Meta:
        verbose_name = _('Training Program')
        verbose_name_plural = _('Training Programs')
        ordering = ('-start_date', )

    # Sets the type of activity as Training Program
    # pylint: disable=W0221
    def save(self, *args, **kwargs):
        self.type_of_activity = TRAINING_PROGRAM
        super(TrainingProgram, self).save(*args, **kwargs)

    # pylint: disable=E1101
    def speakers(self):
        return format_html("<br>".join([
            str(speaker) +
            (" / " + str(speaker.institution.get_person_institution()) if speaker.institution else "")
            for speaker in self.speaker.all()]))

    speakers.allow_tags = True


class SeminarType(models.Model):
    """
    An instance of this class is a type of seminar.

    """
    name = models.CharField(_('Name'), max_length=255)
    image = models.ImageField(_('Image'), upload_to='banners/', blank=True, null=True,
                              help_text=_('Logo for poster. We recommend an image with size 400x100.'))
    qr_code = models.ImageField(_('QR Code'), upload_to='qr_code/', blank=True, null=True,
                                help_text=_('QR code with link to some page.'))

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Type of seminar')
        verbose_name_plural = _('Types of seminar')
        ordering = ('name', )


class Seminar(ProjectActivities):
    """
    An instance of this class is a seminar.

    'class Meta'		Sets the description model (singular and plural) and define ordering of data by date.
    'speakers'          Get the speakers of the seminar and their institutions.
    """
    speaker = models.ManyToManyField(Person, verbose_name=_('Speaker'))
    belongs_to = models.ForeignKey(Meeting, verbose_name=_('Meeting'), blank=True, null=True, on_delete=models.PROTECT)
    category = models.ForeignKey(SeminarType, verbose_name=_('Category'), on_delete=models.PROTECT)
    international_guest_lecturer = models.BooleanField(_('International guest lecturer?'), default=False)
    abstract = models.TextField(_('Abstract'), blank=True, null=True)
    date = models.DateField(_('Date'))
    time = models.TimeField(_('Time'), blank=True, null=True)
    attachment = models.FileField(_('Attachment'), blank=True, null=True)
    room = models.CharField(_('Room'), max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = _('Seminar')
        verbose_name_plural = _('Seminars')
        ordering = ('-date', )

    # Sets the type of activity as Seminar
    # pylint: disable=W0221
    def save(self, *args, **kwargs):
        self.type_of_activity = SEMINAR
        super(Seminar, self).save(*args, **kwargs)

    # pylint: disable=E1101
    def speakers(self):
        return format_html("<br>".join([
            str(speaker) +
            (" / " + str(speaker.institution.get_person_institution()) if speaker.institution else "")
            for speaker in self.speaker.all()]))

    speakers.allow_tags = True

activity/forms.py
from django import forms
from django.forms import TextInput
from activity.models import TrainingProgram, News


class TrainingProgramForm(forms.ModelForm):

    class Meta:
        model = TrainingProgram
        fields = ['other_duration']

    class Media:
        js = ('/static/js/activity.js',)


class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        fields = ['url']
        widgets = {
            'url': TextInput(attrs={'size': 90, 'placeholder': 'http://example.com'}),
        }

templates/report/activity/meetings.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/masked_input/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'js/scientific_mission_report.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Meetings' %}</span></div>
{% endblock %}

{% block content %}
<form role="form" method="post">{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-2 col-sm-2">
            <label>{% trans "Broad audience?" %}</label>
            <select class="form-control" name="broad_audience" id="id_broad_audience">
                <option value="0">----------</option>
                <option value="1">Sim</option>
                <option value="2">Não</option>
            </select>
        </div>
        <div class="col-xs-2 col-sm-2">
            <label>{% trans "Start date" %}</label>
            <input class="datepicker" autocomplete="off" name="start_date" id="id_start_date">
        </div>
        <div class="col-xs-2 col-sm-2">
            <label>{% trans "End date" %}</label>
            <input class="datepicker"  autocomplete="off" name="end_date" id="id_end_date">
        </div>
        <div class="col-xs-2 col-sm-2">
            <br>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary btn-lg" style="font-size:16px;" role="button" id="submit">{% trans "Get report" %}</button>
             </div>
        </div>
    </div>
</div>
</form>

{% endblock %}

templates/report/activity/meetings_report.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Meetings' %}</span></div>
{% endblock %}

{% block content %}
{% if meetings %}
    {% for meeting in meetings %}
        <table class="table table-striped table-bordered">
        <tr><th>{% trans "Title" %}</th><td>{{ meeting.title }}</td></tr>
        <tr><th>{% trans "Description" %}</th><td>{{ meeting.meeting.description }}</td></tr>
        <tr><th>{% trans "Period" %}</th><td>{{ meeting.meeting.start_date }} - {{ meeting.meeting.end_date }}</td></tr>
        {%  if meeting.meeting.participant.count > 0 %}
            <tr><th>{% trans "Number of participants" %}</th><td>{{ meeting.meeting.participant.count }}</td></tr>
        {% endif %}
        {%  if meeting.meeting.url %}
            <tr>
                <th>{% trans "URL" %}</th>
                <td><a href="{{ meeting.meeting.url }}" target="_blank">{{ meeting.meeting.url }}</a></td>
            </tr>
        {% endif %}
        </table>
        <br>
    {% endfor %}
{%  else %}
    {% trans "No meetings found!" %}
{% endif %}

{% endblock %}

templates/report/activity/seminars.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
<script src="{% static 'js/masked_input/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'js/scientific_mission_report.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Seminars' %}</span></div>
{% endblock %}

{% block content %}
<form role="form" method="post">{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4 col-sm-4">
            <label>{% trans "Category" %}</label>
            <select class="form-control" name="category" id="id_category">
                <option value="0"></option>
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col-xs-2 col-sm-2">
            <label>{% trans "Start date" %}</label>
            <input class="datepicker" autocomplete="off" name="start_date" id="id_start_date">
        </div>

        <div class="col-xs-2 col-sm-2">
            <label>{% trans "End date" %}</label>
            <input class="datepicker" autocomplete="off" name="end_date" id="id_end_date">
        </div>

        <div class="col-xs-3 col-sm-3">
            <br>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary btn-lg" style="font-size:16px;" role="button" id="submit">{% trans "Get report" %}</button>
             </div>
        </div>
    </div>
</div>
</form>

{% endblock %}

templates/report/activity/seminars_report.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Seminars' %}</span></div>
{% endblock %}

{% block content %}

{% if seminars %}

    <p>
        <a class="btn btn-primary" href="{% url 'seminars_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&category={{ category }}&extension=.tex"><i class="icon-download icon-white"></i> {% trans 'Download .tex file' %}</a>
        <a class="btn btn-primary" href="{% url 'seminars_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&category={{ category }}&extension=.pdf"><i class="icon-download icon-white"></i> {% trans 'Download .pdf file' %}</a>
    </p>

    <table class="table table-striped table-bordered">
    <tr>
        <th width="40%">{% trans "Title" %}</th><th width="25%">{% trans "Speaker" %}</th>
        <th width="10%">{% trans "Date" %}</th>
    </tr>
    {% for seminar in seminars %}
        <tr>
            <td>{{ seminar.seminar.title }}</td>
            <td>{{ seminar.seminar.speakers }}</td>
            <td>{{ seminar.seminar.date|date:"M d, Y" }}</td>
        </tr>
    {% endfor %}
    </table>

{%  else %}
    {% trans "No seminars found!" %}
{% endif %}

{% endblock %}

templates/report/activity/training_programs.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
<script src="{% static 'js/masked_input/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'js/scientific_mission_report.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Training programs' %}</span></div>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-lg" style="font-size:16px;" role="button" id="submit">{% trans "Get report" %}</button>
    </form>
{% endblock %}

templates/report/activity/training_programs_report.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Training programs' %}</span></div>
{% endblock %}

{% block content %}

{% if training_programs %}
    <p>
        <a class="btn btn-primary" href="{% url 'training_programs_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&extension=.tex"><i class="icon-download icon-white"></i> {% trans 'Download .tex file' %}</a>
        <a class="btn btn-primary" href="{% url 'training_programs_file' %}?start_date={{ start_date|date:"Y-m-d" }}&end_date={{ end_date|date:"Y-m-d" }}&extension=.pdf"><i class="icon-download icon-white"></i> {% trans 'Download .pdf file' %}</a>
    </p>
    <table class="table table-striped table-bordered">
        <tr>
            <th>{% trans "Title" %}</th><th>{% trans "Speaker" %}</th><th>{% trans "Date" %}</th>
            <th>{% trans "Duration" %}</th>
        </tr>
        {% for training in training_programs %}
            <tr>
                <td>{{ training.trainingprogram.title }}</td>
                <td>{{ training.trainingprogram.speakers }}</td>
                {% if training.trainingprogram.end_date %}
                    <td>
                        {{ training.trainingprogram.start_date|date:"M d, Y" }} -
                        {{ training.trainingprogram.end_date|date:"M d, Y" }}
                    </td>
                {% else %}
                    <td>
                        {{ training.trainingprogram.start_date|date:"M d, Y" }}
                    </td>
                {% endif %}
                {% if training.trainingprogram.duration == 'Other' %}
                    <td>{{ training.trainingprogram.other_duration }}</td>
                {% else %}
                    <td>{{ training.trainingprogram.duration }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

{%  else %}
    {% trans "No training programs found!" %}
{% endif %}

{% endblock %}