research/urls.py
from django.conf.urls import url
from research import views


urlpatterns = [

    url(r'^add_periodicals/$', views.add_periodicals, name='add_periodicals'),
    url(r'^add_papers/$', views.add_papers, name='add_papers'),
    url(r'^periodical_published_papers/$', views.periodical_published_papers, name='periodical_published_papers'),
    url(r'^arxiv_papers/$', views.arxiv_papers, name='arxiv_papers'),
    url(r'^event_papers/$', views.event_papers, name='event_papers'),
    url(r'^update_papers/$', views.update_papers, name='update_papers'),

    #  files
    url(r'^articles_file/$', views.articles_file, name='articles_file'),
    url(r'^academic_works_file/$', views.academic_works_file, name='academic_works_file'),

]

sistema/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.utils.translation import ugettext_lazy as _


from helpers.views.show_page import display_documents, display_reports, display_add_content

from .views import language_change
from activity import views as activity_views
from dissemination import views as dissemination_views
from person import views as person_views
from research import views as research_views
from scientific_mission import views as scientific_views

document_patterns = [
    url(r'^anexo5/$', scientific_views.anexo5, name='anexo5'),
    url(r'^anexo6/$', scientific_views.anexo6, name='anexo6'),
    url(r'^anexo7/$', scientific_views.anexo7, name='anexo7'),
    url(r'^anexo9/$', scientific_views.anexo9, name='anexo9'),
    url(r'^certificate/$', activity_views.project_activities_certificate, name='certificate'),
    url(r'^seminars_poster/$', activity_views.seminars_poster, name='seminars_poster'),
]

reports_patterns = [
    url(r'^academic_works/$', research_views.academic_works, name='academic_works'),
    url(r'^articles/$', research_views.articles_report, name='articles'),
    url(r'^dissemination/$', dissemination_views.dissemination_report, name='dissemination_report'),
    url(r'^meetings/$', activity_views.meetings_report, name='meetings_report'),
    url(r'^researchers/$', person_views.researchers, name='researchers_report'),
    url(r'^seminars/$', activity_views.seminars_report, name='seminars_report'),
    url(r'^scientific_mission/$', scientific_views.missions_report, name='missions_report'),
    url(r'^training_programs/$', activity_views.training_programs_report, name='training_programs_report'),
]

content_patterns = [
    url(r'^import_papers/$', research_views.import_papers, name='import_papers'),
    url(r'^citation_names/$', person_views.citation_names, name='citation_names'),
]

urlpatterns = [
    path('', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/password_reset/$', auth_views.PasswordResetView, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView,
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    url(r'^language/(?P<language_code>(?:(?:\w{2})|(?:\w{2}\-\w{2})))$', language_change, name='language_change'),
    url(r'^activity/', include('activity.urls')),
    url(r'^research/', include('research.urls')),
    url(r'^dissemination/', include('dissemination.urls')),
    url(r'^scientific_mission/', include('scientific_mission.urls')),
    url(r'^documents/$', display_documents, name='documents'),
    url(r'^documents/', include(document_patterns)),
    url(r'^reports/$', display_reports, name='reports'),
    url(r'^reports/', include(reports_patterns)),
    url(r'^add_content/$', display_add_content, name='add_content'),
    url(r'^add_content/', include(content_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
if 'suit' not in settings.INSTALLED_APPS:
    admin.site.index_template = 'admin/default_index.html'
    admin.site.app_index_template = 'admin/default_index.html'
    admin.site.index_title = _('Features of the NIRA system')

research/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from person.models import Person, Institution, CitationName


# Defining types of research results
ARTICLE = 'a'
BOOK_OR_CHAPTER = 'b'
TYPE = (
    (ARTICLE, _('Article')),
    (BOOK_OR_CHAPTER, _('Book')),
)

# Teams
SCIENTIFIC = 's'
DISSEMINATION = 'd'
TECHNOLOGY_TRANSFER = 't'
TEAMS = (
    (SCIENTIFIC, _('Scientific')),
    (DISSEMINATION, _('Dissemination')),
    (TECHNOLOGY_TRANSFER, _('Technology transfer'))
)

# Book or chapter
BOOK = 'b'
CHAPTER = 'c'
TYPE_BOOK_OR_CHAPTER = (
    (BOOK, _('Book')),
    (CHAPTER, _('Chapter')),
)

# Published in a journal or in a conference?
PERIODICAL = 'p'
EVENT = 'e'
ARTICLE_TYPE = (
    (PERIODICAL, _('Periodical (Journal or magazine)')),
    (EVENT, _('Event (Conference, congress, meeting, etc)')),
)

FUNDING_CHOICES = ((True, 'Yes'), (False, 'No'))


class ResearchResult(models.Model):
    team = models.CharField(_('Team'), max_length=1, choices=TEAMS)
    person = models.ManyToManyField(Person, through='Author')
    title = models.CharField(_('Title'), max_length=255)
    url = models.URLField(_('URL'), max_length=255, blank=True, null=True)
    note = models.CharField(_('Note'), max_length=255, blank=True, null=True)
    research_result_type = models.CharField(_('Type'), max_length=1, choices=TYPE, blank=True)
    ris_file_authors = models.CharField(_('RIS file authors'), max_length=255, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.title

    def authors(self):
        if self.ris_file_authors and self.ris_file_authors != '':
            return self.ris_file_authors
        else:
            return '; '.join([str(name) for name in CitationName.objects.filter(
                person_id__in=self.person.all(),
                default_name=True)])


class Author(models.Model):
    author = models.ForeignKey(Person, on_delete=models.PROTECT)
    research_result = models.ForeignKey(ResearchResult, on_delete=models.CASCADE)
    order = models.IntegerField(_('Order of author'))

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')
        ordering = ('order', )


class Book(ResearchResult):
    """
    An instance of this class is a book.
    Similar to @book from bibtex.

    """
    type = models.CharField(_('Type'), max_length=1, choices=TYPE_BOOK_OR_CHAPTER)
    publisher = models.ForeignKey(Institution, verbose_name=_('Publisher'), on_delete=models.PROTECT)
    isbn = models.CharField(_('ISBN'), max_length=30, blank=True, null=True)
    volume = models.CharField(_('Volume/Number'), max_length=255, blank=True, null=True)
    serie = models.CharField(_('Serie'), max_length=255, blank=True, null=True)
    edition = models.CharField(_('Edition'), max_length=255, blank=True, null=True)
    doi = models.CharField(_('DOI'), max_length=255, blank=True, null=True)
    date = models.DateField(_('Date'), help_text='Date the book was published.')
    chapter = models.CharField(_('Chapter'), max_length=255, blank=True, null=True)
    start_page = models.IntegerField(_('Start page'), blank=True, null=True)
    end_page = models.IntegerField(_('End page'), blank=True, null=True)

    def __str__(self):
        return u'%s' % self.title

    class Meta:
        verbose_name = _('Book and chapter')
        verbose_name_plural = _('Books and chapters')

    # Sets the type of research result.
    # pylint: disable=W0221
    def save(self, *args, **kwargs):
        if self.pk is None:
            self.research_result_type = BOOK_OR_CHAPTER
        super(Book, self).save(*args, **kwargs)


class Periodical(models.Model):
    """
    An instance of this class is a journal or magazine.

    """
    name = models.CharField(_('Name'), max_length=255)
    acronym = models.CharField(_('Acronym'), max_length=50, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Periodical')
        verbose_name_plural = _('Periodicals')
        ordering = ('name', )


class PeriodicalRISFile(models.Model):
    """
    An instance of this class is how the RIS file called a journal or a magazine.

    """
    periodical = models.ForeignKey(Periodical, on_delete=models.CASCADE)
    name = models.CharField(_('Name'), max_length=255)

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Periodical name on the RIS file')
        verbose_name_plural = _('Periodical name on the RIS file')
        ordering = ('name', )


class Event(models.Model):
    """
    An instance of this class is a conference, a congress, a meeting or a symposium.
    Similar to @proceedings from bibtex.

    """
    name = models.CharField(_('Name'), max_length=255)
    acronym = models.CharField(_('Acronym'), max_length=50, blank=True, null=True)
    publisher = models.ForeignKey(
        Institution,
        verbose_name=_('Publisher'),
        blank=True,
        null=True,
        on_delete=models.PROTECT)
    volume = models.CharField(_('Volume'), max_length=255, blank=True, null=True)
    number = models.CharField(_('Number'), max_length=255, blank=True, null=True)
    start_date = models.DateField(_('Start date of the event'))
    end_date = models.DateField(_('End date of the event'))
    local = models.CharField(_('Local'), max_length=255, help_text='Where the conference was held, '
                                                                   'e.g., "Rio de Janeiro, RJ, Brazil".')

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events (congress, conference, etc.)')
        ordering = ('name', )


class EventRISFile(models.Model):
    """
    An instance of this class is how the RIS file called an event.

    """
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(_('Name'), max_length=255)

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Event name on the RIS file')
        verbose_name_plural = _('Event name on the RIS file')
        ordering = ('name', )


class Article(ResearchResult):
    """
    An instance of this class is a paper in a conference or in a journal.

    """
    periodical = models.ForeignKey(Periodical, verbose_name=_('Periodical'), blank=True, null=True,
                                   on_delete=models.PROTECT)
    event = models.ForeignKey(Event, verbose_name=_('Event'), blank=True, null=True,
                              help_text='Name of the conference, congress, meeting or symposium',
                              on_delete=models.PROTECT)
    type = models.CharField(_('Where?'), max_length=1, blank=True, null=True, choices=ARTICLE_TYPE)
    status = models.CharField(_('Status'), max_length=50)
    hide = models.BooleanField(_('Hide this paper in the report'), default=False)

    def __str__(self):
        return u'%s' % self.title

    def current_status(self):
        if u'p' in self.status:
            return _('Published')
        elif u'a' in self.status:
            return _('Accepted')
        elif u's' in self.status:
            return _('Submitted')
        elif u'd' in self.status:
            return _('Draft')

    def type_of_article(self):
        if self.type == PERIODICAL:
            return _('Periodical')
        elif self.type == EVENT:
            return _('Event')
        else:
            return _('Not defined')

    class Meta:
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')
        ordering = ('title', )

    # Sets the type of research result as article.
    # pylint: disable=W0221
    def save(self, *args, **kwargs):
        if self.pk is None:
            self.research_result_type = ARTICLE
        super(Article, self).save(*args, **kwargs)


class Draft(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    attachment = models.FileField(_('Attachment'), blank=True, null=True)
    date = models.DateField(_('Date'))

    class Meta:
        verbose_name = _('Draft')
        verbose_name_plural = _('Draft')


class Submitted(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    attachment = models.FileField(_('Attachment'), blank=True, null=True)
    date = models.DateField(_('Date'))

    class Meta:
        verbose_name = _('Submitted')
        verbose_name_plural = _('Submitted')


class Accepted(models.Model):
    article = models.OneToOneField(Article, on_delete=models.CASCADE)
    attachment = models.FileField(_('Attachment'), blank=True, null=True)
    date = models.DateField(_('Date'))

    class Meta:
        verbose_name = _('Accepted')
        verbose_name_plural = _('Accepted')


class Published(models.Model):
    article = models.OneToOneField(Article, verbose_name=_('Article'), on_delete=models.CASCADE)
    doi = models.CharField(_('DOI'), max_length=255, blank=True, null=True)
    start_page = models.IntegerField(_('Start page'), blank=True, null=True)
    end_page = models.IntegerField(_('End page'), blank=True, null=True)
    attachment = models.FileField(_('Attachment'), blank=True, null=True)

    class Meta:
        verbose_name = _('Published')
        verbose_name_plural = _('Published')


class PublishedInPeriodical(Published):
    volume = models.CharField(_('Volume'), max_length=255, blank=True, null=True)
    number = models.CharField(_('Number'), max_length=255, blank=True, null=True)
    date = models.DateField(_('Date'))


class TypeAcademicWork(models.Model):
    """
    An instance of this class is a type of academic work.

    """
    name = models.CharField(_('Name'), max_length=255)

    def __str__(self):
        return u'%s' % self.name

    class Meta:
        verbose_name = _('Type of Academic Work')
        verbose_name_plural = _('Types of Academic Work')
        ordering = ('name', )

research/forms.py
from django import forms
from django.forms import TextInput, CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _
from research.models import Article, Book, AcademicWork

# Papers status
DRAFT = 'd'
SUBMITTED = 's'
ACCEPTED = 'a'
PUBLISHED = 'p'
PAPER_STATUS = (
    (DRAFT, _('Draft')),
    (SUBMITTED, _('Submitted')),
    (ACCEPTED, _('Accepted')),
    (PUBLISHED, _('Published')),
)


class ArticleAdminForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['url', 'status']
        widgets = {
            'url': TextInput(attrs={'size': 90, 'placeholder': 'http://example.com'}),
            'status': CheckboxSelectMultiple(choices=PAPER_STATUS)
        }

    class Media:
        js = ('/static/js/articles.js',)
        css = {
            'all': ('/static/css/customization.css',)
        }


class BookAdminForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ['type', 'chapter', 'start_page', 'end_page']

    class Media:
        js = ('/static/js/research.js',)


class AcademicWorkAdminForm(forms.ModelForm):

    class Meta:
        model = AcademicWork
        fields = ['url']
        widgets = {
            'url': TextInput(attrs={'size': 90, 'placeholder': 'http://example.com'}),
        }

    class Media:
        js = ('/static/js/academic_works.js',)


# class AuthorsInlineFormset(forms.models.BaseInlineFormSet):
#     def clean(self):
#         """Check that at least one author has been entered."""
#         super(AuthorsInlineFormset, self).clean()
#         if any(self.errors):
#             return
#         if not any(cleaned_data and not cleaned_data.get('DELETE', False)
#                    for cleaned_data in self.cleaned_data):
#             raise forms.ValidationError(_('You must have at least one author'))

templates/report/research/academic_works.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
<script src="{% static 'js/masked_input/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'js/scientific_mission_report.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a> › <a href="/reports">{% trans 'Reports' %}</a> › <span class="active">{% trans 'Academic Works' %}</span></div>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-lg" style="font-size:16px;" role="button" id="submit">{% trans "Get report" %}</button>
    </form>
{% endblock %}

templates/report/research/add_event_papers.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/select_all_papers.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="/">{% trans 'Home' %}</a><span class="divider">»</span></li>
        <li><a href="/research/import_papers">{% trans 'Import papers' %}</a><span class="divider">»</span></li>
        <li class="active">{% trans 'Papers to import' %}</li>
    </ul>
{% endblock %}

{% block content %}
    <form role="form" method="post" name="event_form" action="{% url 'event_papers' %}">{% csrf_token %}
        {% if event_papers %}
            <strong>{% trans "List of papers from events to add:" %}</strong><br><br>
            <span><input type="checkbox" value='all_papers' id="select_all_papers"> {% trans 'Select all' %}</span>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th>{% trans "Team" %}</th>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Authors" %}</th>
                    <th>{% trans "Event" %}</th>
                    <th>{% trans "Start pg" %}</th>
                    <th>{% trans "End pg" %}</th>
                </tr>
                {% for paper in event_papers %}
                <tr>
                    <td><input type="checkbox" class="checkbox_ris_paper" name="paper_id" value='{{ paper.paper_scholar_id }}'></td>
                    <td>
                        <select class="form-control" name="paper_team_{{ paper.paper_scholar_id }}" id="id_team" style="width: 100px">
                            <option value="none">-----</option>
                            <option value="s" selected="selected">{% trans "Scientific" %}</option>
                            <option value="d">{% trans "Dissemination" %}</option>
                            <option value="t">{% trans "Technology transfer" %}</option>
                        </select>
                    </td>
                    <td><input class="form-control" type="text" name="paper_title_{{ paper.paper_scholar_id }}" style="width: 270px" value="{{ paper.paper_title }}"></td>
                    <td><input class="form-control" type="text" name="paper_author_{{ paper.paper_scholar_id }}" style="width: 260px" value="{{ paper.paper_author }}"></td>
                    {% if events %}
                    <td>
                        <select class="form-control" name="paper_event_{{ paper.paper_scholar_id }}" id="id_event" style="width: 240px">
                            <option value="none">-----</option>
                            {% for event in events %}
                                {% if event.id == paper.event_id %}
                                    <option value="{{ event.id }}" selected="selected">{{ event.name }}</option>
                                {% else %}
                                    <option value="{{ event.id }}">{{ event.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                    {% endif %}
                    <td><input class="form-control" type="text" name="paper_start_page_{{ paper.paper_scholar_id }}" style="width: 60px" value="{{ paper.paper_start_page }}"></td>
                    <td><input class="form-control" type="text" name="paper_end_page_{{ paper.paper_scholar_id }}" style="width: 60px" value="{{ paper.paper_end_page }}"></td>
                </tr>
                {% endfor %}
            </table>
            <button type="submit" class="btn btn-primary btn-lg" name="action" value="add" style="font-size:16px;" role="button">{% trans "Add papers" %}</button>
        {% else %}
            <strong>{% trans "There are no papers from events to add!" %}</strong><br><br>
        {% endif %}

        <div class="btn-group pull-right">
            <button type="submit" class="btn btn-default" name="action" value="back">{% trans "Back" %}</button>
            <button type="submit" class="btn btn-default" name="action" value="next">{% trans "Next" %}</button>
        </div>
    </form>
{% endblock %}

templates/report/research/add_periodical_papers.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static bootstrapped_goodies_tags %}

{% block extrahead %}
    <script src="{% static 'js/add_periodical_papers.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="/">{% trans 'Home' %}</a></li>
        <li><a href="/research/import_papers">{% trans 'Import papers' %}</a></li>
        <li>{% trans 'Papers to import' %}</li>
    </ul>
{% endblock %}

{% block content %}
    <form role="form" method="post" action="{% url 'research.views.add_periodical_papers' %}">{% csrf_token %}
        {% if periodical_papers %}
            <strong>{% trans "List of papers from periodicals to add:" %}</strong><br><br>
            <span><input type="checkbox" value='all_papers' id="select_all_periodical_papers"> {% trans 'Select all' %}</span>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Authors" %}</th>
                    <th>{% trans "Journal" %}</th>
                    <th>{% trans "Vol." %}</th>
                    <th>{% trans "Issue" %}</th>
                    <th>{% trans "Start pg" %}</th>
                    <th>{% trans "End pg" %}</th>
                    <th>{% trans "Date" %}</th>
                </tr>
                {% for paper in periodical_papers %}
                <tr>
                    <td><input type="checkbox" class="checkbox_periodical_papers" name="papers_to_add" value='{{ paper_title }}'></td>
                    <td><input class="form-control" type="text" name="paper_title" style="width: 300px" value="{{ paper.paper_title }}"></td>
                    <td><input class="form-control" type="text" name="paper_author" style="width: 220px" value="{{ paper.paper_author }}"></td>
                    <td>
                        <select class="form-control" name="paper_periodical" id="id_periodical" style="width: 160px">
                            <option value="none">-----</option>
                            {% for periodical in periodicals %}
                                {% if periodical.id == paper.periodical_id %}
                                    <option value="{{ periodical.name }}" selected="selected">{{ periodical.name }}</option>
                                {% else %}
                                    <option value="{{ periodical.name }}">{{ periodical.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                    <td><input class="form-control" type="text" name="paper_volume" style="width: 60px" value="{{ paper.paper_volume }}"></td>
                    <td><input class="form-control" type="text" name="paper_issue" style="width: 40px" value="{{ paper.paper_issue }}"></td>
                    <td><input class="form-control" type="text" name="paper_start_page" style="width: 60px" value="{{ paper.paper_start_page }}"></td>
                    <td><input class="form-control" type="text" name="paper_end_page" style="width: 60px" value="{{ paper.paper_end_page }}"></td>
                    <td><input class="form-control" type="text" name="paper_date" style="width: 80px" value="{{ paper.paper_date }}"></td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <strong>{% trans "No papers from periodicals to be added!" %}</strong><br><br>
        {% endif %}

        <div class="btn-group pull-right">
            <button type="submit" class="btn btn-default" name="action" value="back">Back</button>
            <button type="submit" class="btn btn-default" name="action" value="next">Next</button>
        </div>
    </form>
{% endblock %}

templates/report/research/periodical_published_papers.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/select_all_papers.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li><a href="/">{% trans 'Home' %}</a><span class="divider">»</span></li>
        <li><a href="/research/import_papers">{% trans 'Import papers' %}</a><span class="divider">»</span></li>
        <li class="active">{% trans 'Papers to import' %}</li>
    </ul>
{% endblock %}

{% block content %}
    <form role="form" method="post" name="published_form" action="{% url 'periodical_published_papers' %}">{% csrf_token %}
        {% if periodical_published_papers %}
            <strong>{% trans "List of published papers to add:" %}</strong><br><br>
            <span><input type="checkbox" value='all_papers' id="select_all_papers"> {% trans 'Select all' %}</span>
            <table class="table table-striped">
                <tr>
                    <th></th>
                    <th>{% trans "Team" %}</th>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Authors" %}</th>
                    <th>{% trans "Journal" %}</th>
                    <th>{% trans "Vol." %}</th>
                    <th>{% trans "Issue" %}</th>
                    <th>{% trans "Start pg" %}</th>
                    <th>{% trans "End pg" %}</th>
                    <th>{% trans "Date" %}</th>
                </tr>
                {% for paper in periodical_published_papers %}
                <tr>
                    <td><input type="checkbox" class="checkbox_ris_paper" name="paper_id" value='{{ paper.paper_scholar_id }}'></td>
                    <td>
                        <select class="form-control" name="paper_team_{{ paper.paper_scholar_id }}" id="id_team" style="width: 80px">
                            <option value="none">-----</option>
                            <option value="s" selected="selected">{% trans "Scientific" %}</option>
                            <option value="d">{% trans "Dissemination" %}</option>
                            <option value="t">{% trans "Technology transfer" %}</option>
                        </select>
                    </td>
                    <td><input class="form-control" type="text" name="paper_title_{{ paper.paper_scholar_id }}" style="width: 270px" value="{{ paper.paper_title }}"></td>
                    <td><input class="form-control" type="text" name="paper_author_{{ paper.paper_scholar_id }}" style="width: 180px" value="{{ paper.paper_author }}"></td>
                    <td>
                        <select class="form-control" name="paper_periodical_{{ paper.paper_scholar_id }}" id="id_periodical" style="width: 145px">
                            <option value="none">-----</option>
                            {% for periodical in periodicals %}
                                {% if periodical.id == paper.periodical_id %}
                                    <option value="{{ periodical.id }}" selected="selected">{{ periodical.name }}</option>
                                {% else %}
                                    <option value="{{ periodical.id }}">{{ periodical.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                    <td><input class="form-control" type="text" name="paper_volume_{{ paper.paper_scholar_id }}" style="width: 55px" value="{{ paper.paper_volume }}"></td>
                    <td><input class="form-control" type="text" name="paper_issue_{{ paper.paper_scholar_id }}" style="width: 40px" value="{{ paper.paper_issue }}"></td>
                    <td><input class="form-control" type="text" name="paper_start_page_{{ paper.paper_scholar_id }}" style="width: 55px" value="{{ paper.paper_start_page }}"></td>
                    <td><input class="form-control" type="text" name="paper_end_page_{{ paper.paper_scholar_id }}" style="width: 55px" value="{{ paper.paper_end_page }}"></td>
                    {% if paper.paper_date|date:"Y-m-d" %}
                        <td><input class="form-control" type="text" name="paper_date_{{ paper.paper_scholar_id }}" style="width: 100px" value="{{ paper.paper_date|date:"Y-m-d" }}"></td>
                    {% else %}
                        <td><input class="form-control" type="text" name="paper_date_{{ paper.paper_scholar_id }}" style="width: 100px" value="{{ paper.paper_date }}"></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
            <button type="submit" class="btn btn-primary btn-lg" name="action" value="add" style="font-size:16px;" role="button">{% trans "Add papers" %}</button>
        {% else %}
            <strong>{% trans "There are no published papers to add!" %}</strong><br><br>
        {% endif %}

        <div class="btn-group pull-right">
            <button type="submit" class="btn btn-default" name="action" value="back">{% trans "Back" %}</button>
            <button type="submit" class="btn btn-default" name="action" value="next">{% trans "Next" %}</button>
        </div>
    </form>
{% endblock %}